language: php

php:
  - 7.2
  - 7.3
  - 7.4

sudo: false

env:
  global:
    - PHPUNIT=1

matrix:
  fast_finish: true

  include:
    - php: 7.3
      env: PHPCS=1 PHPUNIT=0

    - php: 7.3
      env: CODECOVERAGE=1 PHPUNIT=0

  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

  - sh -c "if [ '$PHPCS' = '1' ]; then composer require cakephp/cakephp-codesniffer:dev-master; fi"

  - phpenv rehash
  - set +H
  - cp phpunit.xml.dist phpunit.xml

script:
  - sh -c "if [ '$PHPUNIT' = '1' ]; then vendor/bin/phpunit; fi"

  - sh -c "if [ '$PHPCS' = '1' ]; then vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests ./config --ignore=.webroot; fi"

  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then vendor/bin/phpunit --coverage-clover=clover.xml || true; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then wget -O codecov.sh https://codecov.io/bash; fi"
  - sh -c "if [ '$CODECOVERAGE' = '1' ]; then bash codecov.sh; fi"

notifications:
  email: false
