<?php

namespace Alt3\Swagger;

use Cake\Core\BasePlugin;

/**
 * Class Plugin
 * @package Alt3\Swagger
 */
class Plugin extends BasePlugin
{
    /**
     * Add routes for the plugin.
     *
     * The default implementation of this method will include the `config/routes.php` in the plugin if it exists. You
     * can override this method to replace that behavior.
     *
     * @param \Cake\Routing\RouteBuilder $routes The route builder to update.
     * @return void
     */
    public function routes($routes)
    {
        parent::routes($routes); // TODO: Change the autogenerated stub
    }
}